name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95fc4e24604d1544a3831f89ee4da15fd15c96a080ce461c0c97c7e9a74013cf"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
