name = "Iremia"
author = "Greyberet#3484"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d595e8ff407f526b1511292f06f3caa61f11946f67a04f3c58c8f6b04daaae05"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
