name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e66f9e846c62dd48714626f7523c76ea9e99274bafdc4ca6b8d32e6728b00064"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
