name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8184a1c0e6d4efcf3a4c5fa3ee9deb4a8082b289b72ed0d32e0397b07428e262"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
