name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f805077aedfd781f3f03496b0a3cdd6aa2763e1ee9e9c4b02679324a5a0c83a"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
