name = "Iremia"
author = "Greyberet#3484"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d428b10c8ba2f100444be21e43fb6b396d77fe877dfed7f3df886a82c9e03b3"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
