name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cb8e87196d2de03594104565497d3a8a303011603c82abded7d754b9fba0b2f"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
