name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c1522ceb45aee5801f6bf5a3d4f6221d5944656b166158c3f7ddf0e7b9365d"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
