name = "Iremia"
author = "Greyberet#3484"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "febb5cd90e9dd78d2c6bc9bc229cafb2f1743d08621eb372edf478bf7f74b963"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
